ProyectoTest/Models/Carrito.cs
namespace ProyectoTest.Models
{
    public class Carrito
    {
        public int IdCarrito { get; set; }
        public Producto oProducto { get; set; }
        public Usuario oUsuario { get; set; }
    }
}

ProyectoTest/Models/Compra.cs
using System.Collections.Generic;

namespace ProyectoTest.Models
{
    public class Compra
    {
        public int IdCompra { get; set; }
        public int IdUsuario { get; set; }
        public string TotalProducto { get; set; }
        public decimal Total { get; set; }
        public string Dni { get; set; }
        public string Nombres { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string IdDistrito { get; set; }
        public string FechaTexto { get; set; }
        public List<DetalleCompra> oDetalleCompra { get; set; }

    }
}

ProyectoTest/Models/Producto.cs
namespace ProyectoTest.Models
{
    public class Producto
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Marca oMarca { get; set; }
        public Categoria oCategoria { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public string RutaImagen { get; set; }
        public bool Activo { get; set; }
        public string base64 { get; set; }
        public string extension { get; set; }
    }
}

ProyectoTest/Controllers/TiendaController.cs
using ProyectoTest.Logica;
using ProyectoTest.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace ProyectoTest.Controllers
{
    public class TiendaController : Controller
    {
        //API DE RENIEC IMPLEMENTADO
        private readonly string _token = "apis-token-11147.4u8LYVMKh9WjUFeoqYUPyVBQg5CyyQmu";
        private readonly string _apiUrl = "https://api.apis.net.pe/v2/reniec/dni?numero=";

        public async Task<JsonResult> ObtenerDatosPorDni(string dni)
        {
            if (dni.Length != 8 || !dni.All(char.IsDigit))
            {
                return Json(new { success = false, message = "DNI inválido" }, JsonRequestBehavior.AllowGet);
            }

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Add("Accept", "application/json");
                client.DefaultRequestHeaders.Add("Authorization", $"Bearer {_token}");

                var response = await client.GetAsync($"{_apiUrl}{dni}");

                if (response.IsSuccessStatusCode)
                {
                    var responseData = await response.Content.ReadAsStringAsync();
                    var datosDni = JsonConvert.DeserializeObject<dynamic>(responseData);

                    var result = new
                    {
                        success = true,
                        nombres = (string)datosDni.nombres,
                        apellidoPaterno = (string)datosDni.apellidoPaterno,
                        apellidoMaterno = (string)datosDni.apellidoMaterno
                    };

                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Error en la consulta del DNI" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        private static Usuario oUsuario;
        //VISTA
        public ActionResult Index()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");
            else
                oUsuario = (Usuario)Session["Usuario"];

            return View();
        }

        //VISTA
        public ActionResult Producto(int idproducto = 0)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");
            else
                oUsuario = (Usuario)Session["Usuario"];

            Producto oProducto = new Producto();
            List<Producto> oLista = new List<Producto>();

            oLista = ProductoLogica.Instancia.Listar();
            oProducto = (from o in oLista
                         where o.IdProducto == idproducto
                         select new Producto()
                         {
                             IdProducto = o.IdProducto,
                             Nombre = o.Nombre,
                             Descripcion = o.Descripcion,
                             oMarca = o.oMarca,
                             oCategoria = o.oCategoria,
                             Precio = o.Precio,
                             Stock = o.Stock,
                             RutaImagen = o.RutaImagen,
                             base64 = utilidades.convertirBase64(Server.MapPath(o.RutaImagen)),
                             extension = Path.GetExtension(o.RutaImagen).Replace(".", ""),
                             Activo = o.Activo
                         }).FirstOrDefault();

            return View(oProducto);
        }

        //VISTA
        public ActionResult Carrito()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");
            else
                oUsuario = (Usuario)Session["Usuario"];

            return View();
        }

        //VISTA
        public ActionResult Compras()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");
            else
                oUsuario = (Usuario)Session["Usuario"];

            return View();
        }






        [HttpPost]
        public JsonResult ListarProducto(int idcategoria = 0)
        {
            List<Producto> oLista = new List<Producto>();

            oLista = ProductoLogica.Instancia.Listar();
            oLista = (from o in oLista
                      select new Producto()
                      {
                          IdProducto = o.IdProducto,
                          Nombre = o.Nombre,
                          Descripcion = o.Descripcion,
                          oMarca = o.oMarca,
                          oCategoria = o.oCategoria,
                          Precio = o.Precio,
                          Stock = o.Stock,
                          RutaImagen = o.RutaImagen,
                          base64 = utilidades.convertirBase64(Server.MapPath(o.RutaImagen)),
                          extension = Path.GetExtension(o.RutaImagen).Replace(".", ""),
                          Activo = o.Activo
                      }).ToList();

            if (idcategoria != 0)
            {
                oLista = oLista.Where(x => x.oCategoria.IdCategoria == idcategoria).ToList();
            }

            var serializer = new System.Web.Script.Serialization.JavaScriptSerializer();

            var json = Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = 500000000;
            return json;
        }

        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = CategoriaLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult InsertarCarrito(Carrito oCarrito)
        {
            oCarrito.oUsuario = new Usuario() { IdUsuario = oUsuario.IdUsuario };
            int _respuesta = 0;
            _respuesta = CarritoLogica.Instancia.Registrar(oCarrito);
            return Json(new { respuesta = _respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult CantidadCarrito()
        {
            int _respuesta = 0;
            _respuesta = CarritoLogica.Instancia.Cantidad(oUsuario.IdUsuario);
            return Json(new { respuesta = _respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ObtenerCarrito()
        {
            List<Carrito> oLista = new List<Carrito>();
            oLista = CarritoLogica.Instancia.Obtener(oUsuario.IdUsuario);

            if (oLista.Count != 0)
            {
                oLista = (from d in oLista
                          select new Carrito()
                          {
                              IdCarrito = d.IdCarrito,
                              oProducto = new Producto()
                              {
                                  IdProducto = d.oProducto.IdProducto,
                                  Nombre = d.oProducto.Nombre,
                                  oMarca = new Marca() { Descripcion = d.oProducto.oMarca.Descripcion },
                                  Precio = d.oProducto.Precio,
                                  RutaImagen = d.oProducto.RutaImagen,
                                  base64 = utilidades.convertirBase64(Server.MapPath(d.oProducto.RutaImagen)),
                                  extension = Path.GetExtension(d.oProducto.RutaImagen).Replace(".", ""),
                              }
                          }).ToList();
            }


            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCarrito(string IdCarrito, string IdProducto)
        {
            bool respuesta = false;
            respuesta = CarritoLogica.Instancia.Eliminar(IdCarrito, IdProducto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CerrarSesion()
        {
            FormsAuthentication.SignOut();
            Session["Usuario"] = null;
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {
            List<Departamento> oLista = new List<Departamento>();
            oLista = UbigeoLogica.Instancia.ObtenerDepartamento();
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerProvincia(string _IdDepartamento)
        {
            List<Provincia> oLista = new List<Provincia>();
            oLista = UbigeoLogica.Instancia.ObtenerProvincia(_IdDepartamento);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerDistrito(string _IdProvincia, string _IdDepartamento)
        {
            List<Distrito> oLista = new List<Distrito>();
            oLista = UbigeoLogica.Instancia.ObtenerDistrito(_IdProvincia, _IdDepartamento);
            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarCompra(Compra oCompra)
        {
            bool respuesta = false;

            oCompra.IdUsuario = oUsuario.IdUsuario;
            respuesta = CompraLogica.Instancia.Registrar(oCompra);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        //
        [HttpGet]
        public JsonResult ObtenerCompra()
        {
            List<Compra> oLista = new List<Compra>();

            oLista = CarritoLogica.Instancia.ObtenerCompra(oUsuario.IdUsuario);

            oLista = (from c in oLista

ProyectoTest/Views/Tienda/Compras.cshtml
@{
    ViewBag.Title = "Compras";
    Layout = "~/Views/Shared/_Layout_Tienda.cshtml";
}
<style>
    .accordion-button {
        cursor: pointer !important;
    }
</style>
<div class="row mt-5 pt-4">
    <div class="col-12">
        <h4>Mis Compras</h4>
    </div>
</div>
<div class="row mt-2">
    <div class="col-12">
        <div class="card">
            <div class="card-body bg-secondary">

                <div class="accordion" id="accordion_articulos">
                    
                </div>
            </div>
        </div>

    </div>

</div>

@section scripts{
    <script>
        function zeroFill(number, width) {
            width -= number.toString().length;
            if (width > 0) {
                return new Array(width + (/\./.test(number) ? 2 : 1)).join('0') + number;
            }
            return number + ""; // always return a string
        }

        $(document).ready(function () {
           jQuery.ajax({
                url: '@Url.Action("ObtenerCompra", "Tienda")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    console.log(data)
                    if (data.lista != null) {
                        $.each(data.lista, function (i, v) {
                            var accordion_item = $("<div>").addClass("accordion-item");

                            var accordion_header = $("<div>").addClass("accordion-header").append(
                                $("<div>").addClass("accordion-button collapsed").attr({ "data-bs-toggle": "collapse", "data-bs-target": "#collapse" + i, "aria-expanded": "false" }).append(
                                    $("<div>").addClass("d-flex justify-content-between w-100").append(
                                        $("<div>").text("N° " + zeroFill(i + 1, 6)),
                                        $("<div>").addClass("me-4").text("Fecha Compra: " + v.FechaTexto)
                                    )
                                )
                            );

                            var accordion_collapse = $("<div>").attr({ "id": "collapse" + i }).addClass("accordion-collapse collapse");

                            var accordion_body = $("<div>").addClass("accordion-body");
                            $.each(v.oDetalleCompra, function (x, dc) {
                                var d_flex = $("<div>").addClass("d-flex flex-row border p-2").append(
                                                $("<img>").attr({ "src": "data:image/" + dc.oProducto.extension + ";base64," + dc.oProducto.base64,"width":"50"}),
                                                $("<div>").addClass("p-2 bd-highlight").text(dc.oProducto.Nombre),
                                                $("<div>").addClass("p-2 bd-highlight ms-auto").text("Cantidad: " + dc.Cantidad),
                                                $("<div>").addClass("p-2 bd-highlight").text("Total: S/. " + dc.Total)
                                            )
                                accordion_body.append(d_flex);

                            });

                            accordion_body.append(
                                $("<div>").addClass("d-flex justify-content-between bg-light border").append(
                                    $("<div>").addClass("p-2 bd-highlight").text("Total Importe:"),
                                    $("<div>").addClass("p-2 bd-highlight").text("S/. " + v.Total)
                                )
                            );
                            
                            accordion_collapse.append(accordion_body);

                            accordion_item.append(accordion_header);
                            accordion_item.append(accordion_collapse);


                            $("#accordion_articulos").append(accordion_item);
                        });

                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show");
                },
            });
        })
         
    </script>
}

ProyectoTest/Views/Tienda/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Tienda.cshtml";
}
<style>
    /* Estilos para las tarjetas de producto */
    .card {
        border: none;
        border-radius: 12px;
        overflow: hidden;
        transition: all 0.3s ease;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        }

    .card-img-top {
        height: 280px;
        object-fit: cover;
        transition: transform 0.3s ease;
    }

    .card:hover .card-img-top {
        transform: scale(1.05);
    }

    .card-body {
        padding: 1.5rem;
    }

    .card h5.fw-bolder {
        font-size: 1.1rem;
        color: #2d3748;
        margin-bottom: 0.5rem;
    }

    /* Estilos para los botones */
    .btn-outline-dark {
        border: 2px solid #2d3748;
        color: #2d3748;
        font-weight: 500;
        padding: 0.5rem 1rem;
        transition: all 0.3s ease;
    }

        .btn-outline-dark:hover {
            background-color: #2d3748;
            color: #ffffff;
            transform: translateY(-1px);
        }

    .btn-agregar-carrito {
        background-color: #48bb78;
        border-color: #48bb78;
        color: #ffffff;
    }

        .btn-agregar-carrito:hover {
            background-color: #38a169;
            border-color: #38a169;
        }

    /* Estilos para el modal */
    .modal-content {
        border: none;
        border-radius: 12px;
        overflow: hidden;
    }

    .modal-header {
        background: #f7fafc;
        border-bottom: 1px solid #e2e8f0;
        padding: 1.5rem;
    }

    .modal-title {
        color: #2d3748;
        font-weight: 600;
    }

    .modal-body {
        padding: 1.5rem;
    }

    .btn-categoria {
        transition: all 0.3s ease;
        border-radius: 6px;
        font-weight: 500;
    }

        .btn-categoria:hover {
            transform: translateY(-1px);
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }

    /* Responsive adjustments */
    @@media (max-width: 768px) {
        .page-heading {
            padding: 2rem 0;
        }

            .page-heading h3 {
                font-size: 2rem;
            }

        .properties-filter {
            gap: 0.5rem;
        }

            .properties-filter li a {
                padding: 0.5rem 1rem;
                font-size: 0.9rem;
            }

        .card-img-top {
            height: 220px;
        }
    }

    /* Loading overlay personalizado */
    .loadingoverlay {
        background: rgba(255, 255, 255, 0.9) !important;
    }

    .loadingoverlay_element {
        border: 3px solid #667eea;
        border-top-color: transparent;
        border-radius: 50%;
    }
</style>
<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <span class="breadcrumb"><a href="#">Home</a> / Tienda Online</span>
                <h3>Tienda Online</h3>
            </div>
        </div>
    </div>
</div>

<div class="section properties">
    <div class="container">
        <ul class="properties-filter">
            <li>
                <a class="is_active" href="#!" data-filter="*">Ver Todo</a>
            </li>
            <li>
                <a href="#!" data-filter=".Collares">Collares</a>
            </li>
            <li>
                <a href="#!" data-filter=".Pulseras">Pulseras</a>
            </li>
        </ul>

        <div class="py-2">
            <div class="container px-2 px-lg-2 mt-5">
                <div id="catalogo-productos" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                </div>
            </div>
        </div>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Seleccione una Categoría</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row row-categoria">
                    </div>

                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div>
    </div>

    @section scripts{

        <script>

        $(".btn-ver-categoria").click(function () {
            jQuery.ajax({
                url: '@Url.Action("ListarCategoria", "Tienda")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $(".row-categoria").html("");
                    $(".modal-body").LoadingOverlay("hide");
                    if (data.data != null) {
                        $("<div>").addClass("col-4").append(
                            $("<button>").addClass("btn btn-outline-primary btn-categoria m-1 w-100").text("Ver Todos").attr({ "onclick":"listarProductos(0)"})
                        ).appendTo(".row-categoria")

                        $.each(data.data, function (i, item) {
                            $("<div>").addClass("col-4").append(
                                $("<button>").addClass("btn btn-outline-primary btn-categoria m-1 w-100").text(item.Descripcion).attr({ "onclick": "listarProductos("+ item.IdCategoria +")" })
                            ).appendTo(".row-categoria")
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show");
                },
            });

            $('#exampleModal').modal('show');
        });

        $(document).ready(function () {
            listarProductos(0);
        })

        $(document).on('click', '.btn-detalle', function (event) {
            var json = $(this).data("elemento")
            window.location.href = "@Url.Action("Producto", "Tienda")" + "?idproducto=" + json.IdProducto;
        });

        $(document).on('click', '.btn-categoria', function (event) {
            $('#exampleModal').modal('hide');
        });


        function listarProductos(_idcategoria) {
            jQuery.ajax({
                url: '@Url.Action("ListarProducto", "Tienda")',
                type: "POST",
                data: JSON.stringify({ idcategoria: _idcategoria}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("#catalogo-productos").html("");

                    $("#catalogo-productos").LoadingOverlay("hide");
                    if (data.data != null) {

                        $.each(data.data, function (i, item) {
                            //catalogo-productos
                            $("<div>").addClass("col mb-5").append(
                                $("<div>").addClass("card h-100").append(
                                    $("<img>").addClass("card-img-top").attr({ "src": "data:image/" + item.extension + ";base64," + item.base64 }),
                                    //Product details
                                    $("<div>").addClass("card-body p-4").append(
                                        $("<div>").addClass("text-center").append(
                                            $("<h5>").addClass("fw-bolder").text(item.Nombre),
                                            "S/. " + item.Precio
                                        )
                                    ),
                                    //Product actions
                                    $("<div>").addClass("card-footer p-4 pt-0 border-top-0 bg-transparent").append(
                                        $("<div>").addClass("d-grid d-md-grid gap-2 d-md-block align-items-center text-center").append(
                                            $("<button>").addClass("btn btn-outline-dark mt-auto btn-detalle").text("Ver Detalle").attr({ "data-elemento": JSON.stringify(item) }),
                                           @{
                                               if (((ProyectoTest.Models.Usuario)Session["Usuario"]).EsAdministrador == false) {
                                                    @:$("<button>").addClass("btn btn-outline-dark mt-auto btn-agregar-carrito").data("idproducto", item.IdProducto).text("Agregar al carrito")
                                               }
                                           }

                                        )
                                    )
                                )

                            ).appendTo("#catalogo-productos");
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                    $("#catalogo-productos").LoadingOverlay("show");
                },
            });
        }

        </script>



    }

ProyectoTest/Views/Tienda/Producto.cshtml
@model ProyectoTest.Models.Producto
@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/_Layout_Tienda.cshtml";
}

<style>
    /* Estilos generales y variables */
    :root {
        --primary-color: #333;
        --accent-color: #ff4444;
        --success-color: #28a745;
        --text-color: #666;
        --light-bg: #f8f9fa;
    }

    /* Contenedor principal con efecto de tarjeta */
    .product-section {
        padding: 3rem 0;
        background-color: var(--light-bg);
        min-height: 80vh;
        display: flex;
        align-items: center;
    }

    .product-container {
        background: white;
        border-radius: 15px;
        padding: 2rem;
        box-shadow: 0 5px 15px rgba(0,0,0,0.05);
        max-width: 1200px;
        margin: 0 auto;
    }

    /* Estilos de la imagen */
    .product-image-container {
        position: relative;
        border-radius: 12px;
        overflow: hidden;
    }

    .product-image {
        width: 100%;
        height: auto;
        border-radius: 12px;
        transition: transform 0.5s ease;
        object-fit: cover;
    }

    .product-image:hover {
        transform: scale(1.05);
    }

    /* Información del producto */
    .brand-name {
        color: var(--accent-color);
        font-size: 0.9rem;
        text-transform: uppercase;
        letter-spacing: 2px;
        margin-bottom: 0.5rem;
        font-weight: 600;
    }

    .product-title {
        font-size: 2.5rem;
        font-weight: 700;
        color: var(--primary-color);
        margin-bottom: 1rem;
        line-height: 1.2;
    }

    .product-price {
        font-size: 1.8rem;
        color: var(--primary-color);
        font-weight: 700;
        margin-bottom: 1.5rem;
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }

    .price-currency {
        font-size: 1rem;
        color: var(--text-color);
    }

    .product-description {
        font-size: 1rem;
        line-height: 1.8;
        color: var(--text-color);
        margin-bottom: 2rem;
        padding-right: 2rem;
    }

    /* Botones con mejor diseño */
    .buttons-container {
        display: flex;
        gap: 1rem;
        margin-top: 2rem;
    }

    .btn-back {
        background-color: #fff;
        color: var(--accent-color);
        border: 2px solid var(--accent-color);
        padding: 1rem 2rem;
        border-radius: 8px;
        transition: all 0.3s ease;
        text-decoration: none;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-weight: 600;
        width: 180px;
    }

    .btn-back:hover {
        background-color: var(--accent-color);
        color: white;
        transform: translateY(-2px);
    }

    .btn-cart {
        background-color: var(--success-color);
        color: white;
        padding: 1rem 2rem;
        border-radius: 8px;
        border: none;
        transition: all 0.3s ease;
        cursor: pointer;
        font-weight: 600;
        width: 180px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 0.5rem;
    }

    .btn-cart:hover {
        background-color: #218838;
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(40, 167, 69, 0.2);
    }

    /* Zoom effect container */
    .zoom-container {
        position: relative;
        overflow: hidden;
        border-radius: 12px;
    }

    /* Responsive design */
    @@media (max-width: 768px) {
        .product-container {
            padding: 1rem;
        }

        .product-title {
            font-size: 1.8rem;
        }

        .product-description {
            padding-right: 0;
        }

        .buttons-container {
            flex-direction: column;
        }

        .btn-back, .btn-cart {
            width: 100%;
        }
    }
</style>

<section class="product-section">
    <div class="product-container">
        <div class="row gx-5 align-items-center">
            <div class="col-md-6">
                <div class="zoom-container mb-4">
                    <img class="product-image"
                         src="data:image/@Html.DisplayTextFor(model => model.extension);base64,@Html.DisplayTextFor(model => model.base64)"
                         alt="@Html.DisplayTextFor(model => model.Nombre)">
                </div>
            </div>
            <div class="col-md-6">
                <div class="brand-name">@Html.DisplayTextFor(model => model.oMarca.Descripcion)</div>
                <h1 class="product-title">@Html.DisplayTextFor(model => model.Nombre)</h1>
                <div class="product-price">
                    <span class="price-currency">S/.</span>
                    <span>@Html.DisplayTextFor(model => model.Precio)</span>
                </div>
                <p class="product-description">@Html.DisplayTextFor(model => model.Descripcion)</p>
                <div class="buttons-container">
                    <a href="@Url.Action("Index", "Tienda")" class="btn-back">
                        <i class="fas fa-arrow-left me-2"></i> Volver
                    </a>
                    @if (((ProyectoTest.Models.Usuario)Session["Usuario"]).EsAdministrador == false)
                    {
                        <button class="btn-cart btn-agregar-carrito"
                                type="button"
                                data-idproducto="@Html.DisplayTextFor(model => model.IdProducto)">
                            <i class="fas fa-shopping-cart"></i>
                            <span>Agregar al carrito</span>
                        </button>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts {
    <script>
        // Efecto de zoom suave en la imagen
        document.addEventListener('DOMContentLoaded', function() {
            const productImage = document.querySelector('.product-image');

            if (productImage) {
                productImage.addEventListener('mousemove', function(e) {
                    const { left, top, width, height } = this.getBoundingClientRect();
                    const x = (e.clientX - left) / width;
                    const y = (e.clientY - top) / height;

                    this.style.transformOrigin = `${x * 100}% ${y * 100}%`;
                });
            }
        });
    </script>
}